### ISSUE TITLE
Auth0 Step doesnt work anymore

### ISSUE THREAD

**Issue by krangerich** [trondhindenes/Kubernetes-Auth0#3]
I followed https://github.com/trondhindenes/Kubernetes-Auth0/blob/master/docs/01-auth0.md and the rule didn't add the groups  as supposed to. https://openidconnect.net/ only shows the default token

**Comment by fbuchmeier** [comment]
This is the exact same issue I am currently facing. It is possible to add the groups using a custom namespace like described here: https://community.auth0.com/t/authorization-extension-groups-not-in-jwt/22294/8

An example would be:
```
function adddGroupsToIdToken(user, context, callback) {
  const namespace = 'https://example.com/';
  context.idToken[namespace + 'groups'] = user.groups;
  console.log(context.idToken);
  callback(null, user, context);
}
```

However, I do not yet know how I can get my oauth proxy (https://github.com/oauth2-proxy/oauth2-proxy) to use this custom group claim (?) instead of just `groups`.

@krangerich do you have any leads on thsi?
